export const RelayEvents = {
  SESSION_STARTED: "SESSION_STARTED",

  SESSION_ENDED: "SESSION_ENDED",

  PAGE_VIEW: "PAGE_VIEW",

  CHAT_WIDGET_LOADED: "CHAT_WIDGET_LOADED",

  CHAT_OPENED: "CHAT_OPENED",

  CHAT_CLOSED: "CHAT_CLOSED",

  MESSAGE_SENT: "MESSAGE_SENT",

  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
} as const;