import React from 'react';

export const Terms: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12 text-slate-800">
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-sm text-slate-500 mb-8">Last updated: August 31, 2026</p>

      <section className="space-y-6 text-slate-600 leading-relaxed">
        <h2 className="text-xl font-semibold text-slate-900 mt-6">1. Acceptance of Terms</h2>
        <p>
          By accessing or using Relay, installing our script tag, or uploading documents, you agree to be bound by these Terms of Service.
        </p>

        <h2 className="text-xl font-semibold text-slate-900 mt-6">2. Script Embed & API Key Responsibilities</h2>
        <p>
          You are responsible for protecting your API keys and ensuring that the Relay script tag is embedded legally on websites you own or operate.
        </p>

        <h2 className="text-xl font-semibold text-slate-900 mt-6">3. Acceptable Use of AI & Knowledge Base</h2>
        <p>
          You agree not to upload content that contains illegal material, malware, personally identifiable information (PII) of third parties without consent, or malicious code intended to exploit LLM prompt boundaries.
        </p>

        <h2 className="text-xl font-semibold text-slate-900 mt-6">4. Service Availability & Limitations</h2>
        <p>
          Relay is provided "as is". AI responses generated through OpenRouter integrations are non-deterministic, and Relay is not liable for inaccurate outputs generated by custom AI assistants.
        </p>
      </section>
    </div>
  );
};